### ISSUE TITLE
AIX builds failing due to /tmp/sh-np.* file leakage...?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#929]
**Platform:**
AIX

**Architecture:**
ppc

AIX builds are current failing with weird errors:
/tmp//sh-np.MnrMic: ambiguous redirect

Examining machine shows /tmp contains a huge number of these sh-np.* files...

**Comment by karianna** [comment]
Hi @sxa555 can this be closed now or do we need to apply @andrew-m-leonard 's script?

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/view/Tooling/job/SXA-processCheck was modified to add a section that will delete these files 

However I'm somewhat unwilling to close this until we understand why they are being left around as it seems indiciative of another problem which we didn't seem to have in the past. The mitigation in place is more of a hack than a proper solution to this issue.

**Comment by AdamBrousseau** [comment]
I doubt this is a new issue. We've always had this issue on the OpenJ9 AIX farm machines. I think it's related to Bash on AIX. I had a google a while back and that's where I ended up.

cc @sej-jackson our resident AIX expert.

**Comment by sxa555** [comment]
Unclear on whether it's new but we only spotted it recently when it was filling up the filesystems and causing havoc

**Comment by sxa555** [comment]
Since the `test` tag isn't currently on the new machine [test-osuosl-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/test-osuosl-ppc64-aix-71-1/) this machine has succumbed to the same problem. Once we figure out why that machine isn't running tests properly we can resolve it, but for today I'm clearing up the files manually as a one-off

**Comment by sxa555** [comment]
Cleared out the "test" machine yesterday - problems still persists therefore not closing yet

**Comment by aixtools** [comment]
Looks like something I can look into. Which (osu) system may I examine to try and track-down the root cause - and from there look for a solution.

**Comment by aixtools** [comment]
I noticed this on ojdk06 - 14036 (or something like that) on 30 November.

```
root@p9-aix1-ojdk06:[/tmp]ls sh-np.?????? | wc
  14036   14036  182468
```
Also seeing these temporary directories - not getting cleaned up:
```
drwx------ 2 root system     256 Nov 30 18:41 tmp10360911816276463896
drwx------ 2 root system     256 Nov 30 18:41 tmp10508621662968139732
drwx------ 2 root system     256 Nov 30 18:41 tmp10768443691023794692
drwx------ 2 root system     256 Nov 30 18:41 tmp11201920133139327898
drwx------ 2 root system     256 Nov 30 18:41 tmp12819757122282168306
drwx------ 2 root system     256 Nov 30 18:41 tmp13383837127928177339
drwx------ 2 root system     256 Nov 30 18:41 tmp1487121186373742208
drwx------ 2 root system     256 Nov 30 18:41 tmp16445509965242914812
drwx------ 2 root system     256 Nov 30 18:41 tmp16693781886634834416
drwx------ 2 root system     256 Nov 30 18:41 tmp3064773284354773756
drwx------ 2 root system     256 Nov 30 18:41 tmp4549286212113477752
drwx------ 2 root system     256 Nov 30 18:41 tmp4843343999433649838
drwx------ 2 root system     256 Nov 30 18:41 tmp5188870037535696976
drwx------ 2 root system     256 Nov 30 18:41 tmp5382437659535518126
drwx------ 2 root system     256 Nov 30 18:41 tmp5453698676258375838
drwx------ 2 root system     256 Nov 30 18:41 tmp5868098367571854899
drwx------ 2 root system     256 Nov 30 18:41 tmp8986010931242472156
drwx------ 2 root system     256 Nov 30 18:41 tmp9400983853911607329
```

@Haroon - any idea what command/trial you started on 30 Nov?

```
root@p9-aix1-ojdk06:[/tmp]grep TZ /etc/environment
TZ=UTC0
```

**Comment by sxa** [comment]
@aixtools I think you meant to tag @Haroon-Khel :-)

**Comment by aixtools** [comment]
Today I looked at ojdk01 and ojdk02: there were 274k and 1780k sh-np-* (p) files, respectively.

OJDK01 is cleaned up, OJDK02 - still working on that.

Basically, what I shall do - as a band-aid, not as a cure. is add some cronjobs to cleanup /tmp on a regular basis of these special files (p, s and directories) - so that /tmp does have these leftovers slowing the systems down.

This should fix any build-failures related to this.

Perhaps as a new issue: WHY are these /tmp files and directories not getting cleaned up automatically.

I'll post again when I have that manual change - and perhaps leave this open while _we_ wait for an update the the ansible playbooks to add the cronjobs needed.

**Comment by sxa** [comment]
I've also adjusted https://ci.adoptopenjdk.net/job/SXA-processCheck/ which should have detected and remove any owned by jenkins on a weekly basis, although it was failing because there were too many of them :'(

**Comment by aixtools** [comment]
The root cause is an old version of bash (4.3 on build-osuosl-aix71-ppc64-{1,2}. On the other AIX nodes at osuosl bash-5 is being used, that this particular issue is not occurring.

On build-{1,2) I am now running:

```
##### Remove sh-np-* p-files from /tmp - older than 1 day
0 0 * * * /usr/bin/find /tmp -type p -mtime +1 -exec rm {} \;
##### Remove jenkins leakage from /tmp
##### Note - an extra day is needed for the directories - as removing files modifies mtime
0 0 * * * /usr/bin/find /tmp -user jenkins -mtime +1 ! -type d -exec rm {} \;
5 0 * * * /usr/bin/find /tmp -user jenkins -mtime +1 -type d | sort -r | xargs rmdir >/dev/null 2>/dev/null

I have also tested using `/usr/bin/skulker` - which is even more vigorous in removing files older than 1 day.

IMHO: updating the playbooks is not the correct solution. Updating OS and OSS to latest/more current OS and OSS levels is the logical step.

IMHO: this issue is resolved (manual) steps - and the root cause is known.
```

**Comment by sxa** [comment]
I'd be in favour of using `skulker` to do the job too. We should add one of the options to the playbooks so this gets deployed to all machines before closing this issue

**Comment by aixtools** [comment]
Fixed by #2049

**Comment by sxa** [comment]
Going to reopen this in place of the new issue https://github.com/adoptium/infrastructure/issues/2640 since the solution has sadly not resolved the original problem in all cases, and it seems to have become more prevelant recently. The [above PR](https://github.com/adoptium/infrastructure/issues/2640) will hopefully help by clearing out all the files at the start of each jenkins build, which will avoid any temporary files created by previous `bash` instances from interfering with the named pipe ifilenames from the next run.

**Comment by sxa** [comment]
Ran some tests on Friday by re-running https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/ multiple times in succession (All on https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1). They all failed although not at the same part in the build process

Job | ambiguous redirect file | After what operation
--- | --- | ---
[81](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/81/console) | `/tmp//sh-np.L4Gaac` | Creating `support/test/hotspot/jtreg/native/bin/sigtest` 
[82](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/82/console) |  `/tmp//sh-np.K4Gaac` | Creating `libsplashscreen.a `
[83](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/83/console) | `/tmp//sh-np.b4Gaac` | Creating `support/test/hotspot/jtreg/native/bin/sigtest`
[84](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/84/console)  | `/tmp//sh-np.Xr9qab` | Creating `libsplashscreen.a`
[85](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/85/console)  | `/tmp//sh-np.-r9qab` | `Updating support/src.zip`

![image](https://user-images.githubusercontent.com/6487691/177114353-93b691b4-06c9-4c95-a827-dfdaa7aaf6a3.png)

**Comment by sxa** [comment]
Three builds of [JDK17u](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin) in a row today without problems after the PR was merged.

Optimistically closing again ...
